const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const providers=[
{id:1,name:'Maria J.',initials:'MJ',avatar:'blue',role:'Painter · General labor',skills:['Painting','Drywall touch-up','General labor'],rate:34,distance:1.8,eta:'18 min',available:'now',verified:true,background:true,rating:4.9,jobs:128,repeat:42,bio:'Interior painting, prep, touch-ups and general household project help. I bring basic painting tools and can start quickly when Available Now is on.'},
{id:2,name:'David T.',initials:'DT',avatar:'green',role:'Furniture assembly · Moving help',skills:['Assembly','Moving','Mounting'],rate:30,distance:3.1,eta:'24 min',available:'now',verified:true,background:false,rating:4.8,jobs:73,repeat:19,bio:'Furniture assembly and moving help with a focus on careful handling, clear communication and fast turnaround.'},
{id:3,name:'Andre K.',initials:'AK',avatar:'amber',role:'Yard work · Cleanup',skills:['Yard work','Cleanup','General labor'],rate:28,distance:4.7,eta:'31 min',available:'now',verified:true,background:false,rating:4.9,jobs:91,repeat:28,bio:'Outdoor cleanup, leaf removal, hauling assistance and general labor. Available for short-notice jobs when my live status is on.'},
{id:4,name:'Elena R.',initials:'ER',avatar:'purple',role:'Cleaning · Organization',skills:['Cleaning','Organization','Move-out cleaning'],rate:32,distance:2.6,eta:'Today at 6 PM',available:'today',verified:true,background:true,rating:5.0,jobs:156,repeat:61,bio:'Residential cleaning, deep cleaning and organization with flexible scheduling and repeat-service availability.'},
{id:5,name:'Chris M.',initials:'CM',avatar:'rose',role:'Handyman · Assembly',skills:['Handyman','Assembly','Minor repairs'],rate:42,distance:7.2,eta:'Today at 4 PM',available:'today',verified:true,background:false,rating:4.7,jobs:64,repeat:14,bio:'General household repair and assembly. I list exactly what I can do and what tools I carry so customers can book with confidence.'},
{id:6,name:'Northside Tech',initials:'NT',avatar:'cyan',role:'Computer help · Home technology',skills:['Computer help','Wi-Fi','Device setup'],rate:55,distance:5.4,eta:'Today at 7 PM',available:'today',verified:true,background:true,rating:4.9,jobs:212,repeat:88,bio:'Local technology support for home networks, computer setup, printers, smart devices and troubleshooting.'}
];
const categories=[['🎨','Painting','Walls, rooms and touch-ups'],['📦','Moving','Loading and moving help'],['🧹','Cleaning','Home and business cleaning'],['🪛','Assembly','Furniture and mounting'],['🌿','Yard work','Cleanup and outdoor help'],['💻','Computer help','Setup and troubleshooting']];
let jobs=[
{id:101,title:'Help unload a moving truck',category:'Moving',distance:'1.9 mi',when:'Today · 5:30 PM',budget:'$80–$120',desc:'Need two people to help unload boxes and furniture from a 16-foot truck. About two hours.'},
{id:102,title:'Paint one bedroom',category:'Painting',distance:'3.6 mi',when:'Tomorrow morning',budget:'$180',desc:'Room is empty and paint is already purchased. Need prep, two coats and cleanup.'},
{id:103,title:'Assemble desk and bookcase',category:'Assembly',distance:'2.2 mi',when:'This week',budget:'$90',desc:'Flat-pack desk and bookcase. Flexible weekday timing.'},
{id:104,title:'Backyard cleanup',category:'Yard work',distance:'4.1 mi',when:'Saturday',budget:'$150–$220',desc:'Leaves, branches and general cleanup. Bags provided.'}
];
let selectedProvider=null,workerAvailable=localStorage.getItem('taskwell-available')==='1';
function money(n){return '$'+n+'/hr'}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2200)}
function miniProvider(p){return `<div class="mini-provider"><div class="avatar ${p.avatar}">${p.initials}</div><div class="grow"><strong>${p.name}</strong><small>${p.role}</small></div><span class="badge live">${p.eta}</span></div>`}
function providerCard(p){return `<article class="provider-card"><div class="provider-top"><div class="avatar ${p.avatar}">${p.initials}</div><div class="provider-main"><div class="provider-name">${p.name}</div><div class="provider-role">${p.role}</div></div><button class="iconbtn save-provider" data-id="${p.id}" title="Save worker">♡</button></div><div class="badge-row">${p.available==='now'?'<span class="badge live">● Available now</span>':'<span class="badge">Available today</span>'}${p.verified?'<span class="badge verify">✓ ID verified</span>':''}${p.background?'<span class="badge">✓ Background checked</span>':''}<span class="badge rating">★ ${p.rating}</span></div><div class="provider-meta"><div class="metric"><small>Rate</small><strong>${money(p.rate)}</strong></div><div class="metric"><small>${p.available==='now'?'Arrival':'Distance'}</small><strong>${p.available==='now'?p.eta:p.distance+' mi'}</strong></div></div><div class="provider-actions"><button class="btn secondary view-provider" data-id="${p.id}">View profile</button><button class="btn primary hire-provider" data-id="${p.id}">${p.available==='now'?'Hire now':'Request'}</button></div></article>`}
function jobCard(j,worker=false){return `<article class="job-card"><div class="badge-row"><span class="badge">${j.category}</span><span class="badge">${j.distance}</span></div><h3>${j.title}</h3><p>${j.desc}</p><div class="job-meta"><span>◷ ${j.when}</span><span>💵 ${j.budget}</span></div><button class="btn ${worker?'primary':'secondary'} ${worker?'apply-job':'view-job'}" data-id="${j.id}">${worker?'Apply':'View job'}</button></article>`}
function renderHome(){$('#miniLive').innerHTML=providers.filter(p=>p.available==='now').slice(0,3).map(miniProvider).join('');$('#categoryGrid').innerHTML=categories.map(c=>`<button class="category quickcat" data-cat="${c[1]}"><div class="ico">${c[0]}</div><strong>${c[1]}</strong><small>${c[2]}</small></button>`).join('');$('#homeProviders').innerHTML=providers.filter(p=>p.available==='now').slice(0,3).map(providerCard).join('');bindDynamic()}
function renderPeople(){const term=($('#peopleSearch')?.value||'').toLowerCase(),availability=$('#availabilityFilter')?.value||'all',dist=Number($('#distanceFilter')?.value||999),verify=$('#verifyFilter')?.value||'all';const filtered=providers.filter(p=>(!term||(p.name+' '+p.role+' '+p.skills.join(' ')).toLowerCase().includes(term))&&(availability==='all'||p.available===availability)&&p.distance<=dist&&(verify==='all'||p.verified));$('#resultCount').textContent=`${filtered.length} provider${filtered.length===1?'':'s'} found near Allentown`;$('#peopleGrid').innerHTML=filtered.length?filtered.map(providerCard).join(''):`<div class="job-card" style="grid-column:1/-1"><h3>No exact matches right now</h3><p>Browse people available later today, remove a filter, or post the job so nearby workers can apply.</p><button class="btn primary" id="emptyPost">Post the job</button></div>`;bindDynamic()}
function renderJobs(){$('#jobsList').innerHTML=jobs.map(j=>jobCard(j,false)).join('');$('#workerJobs').innerHTML=jobs.map(j=>jobCard(j,true)).join('');bindDynamic()}
function renderProfile(id){const p=providers.find(x=>x.id===Number(id));if(!p)return;selectedProvider=p;$('#profileContent').innerHTML=`<div class="profile-shell"><div class="profile-main"><div class="profile-card"><div class="profile-hero"><div class="avatar ${p.avatar}">${p.initials}</div><div><h2>${p.name}</h2><p>${p.role}</p><div class="badge-row">${p.available==='now'?'<span class="badge live">● Available now</span>':''}<span class="badge verify">✓ ID verified</span>${p.background?'<span class="badge">✓ Background checked</span>':''}<span class="badge rating">★ ${p.rating}</span></div></div></div><p class="muted">${p.bio}</p></div><div class="profile-card"><h3>Services</h3><div class="quicklinks">${p.skills.map(s=>`<span class="chip">${s}</span>`).join('')}</div></div><div class="profile-card"><h3>Recent work</h3><div class="portfolio"><div class="portfolio-item">Project photo</div><div class="portfolio-item">Project photo</div><div class="portfolio-item">Project photo</div></div></div><div class="profile-card"><h3>Reviews</h3><div class="review"><div class="review-top"><strong>★★★★★</strong><small>2 weeks ago</small></div><p>Showed up on time, communicated clearly and finished faster than expected.</p><small>Verified completed job</small></div><div class="review"><div class="review-top"><strong>★★★★★</strong><small>1 month ago</small></div><p>Great work and very easy to coordinate with through the site.</p><small>Verified completed job</small></div></div></div><aside class="profile-side"><div class="profile-card"><div class="metric"><small>Rate</small><strong>${money(p.rate)}</strong></div><div class="metric" style="margin-top:10px"><small>${p.available==='now'?'Estimated arrival':'Next availability'}</small><strong>${p.eta}</strong></div><button class="btn primary full hire-provider" data-id="${p.id}" style="margin-top:14px">${p.available==='now'?'Hire now':'Request for later'}</button><button class="btn secondary full save-provider" data-id="${p.id}" style="margin-top:8px">♡ Save worker</button></div><div class="profile-card"><h3>Marketplace history</h3><div class="provider-meta"><div class="metric"><small>Completed</small><strong>${p.jobs}</strong></div><div class="metric"><small>Repeat hires</small><strong>${p.repeat}</strong></div></div><p class="muted">Ranking cannot be purchased. Search position is based on relevance, availability, distance and earned reputation.</p></div></aside></div>`;bindDynamic()}
function switchView(name){$$('.view').forEach(v=>v.classList.remove('active'));$('#view-'+name)?.classList.add('active');$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));scrollTo({top:0,behavior:'smooth'});if(name==='people')renderPeople();if(name==='jobs'||name==='work')renderJobs()}
function openHire(id){selectedProvider=providers.find(p=>p.id===Number(id));$('#hireName').textContent=selectedProvider.name;$('#hireTask').value='';$('#hireFormWrap').classList.remove('hidden');$('#hireSuccess').classList.add('hidden');$('#hireModal').classList.add('show')}
function openJob(){$('#jobTitle').value='';$('#jobDesc').value='';$('#jobBudget').value='';$('#jobFormWrap').classList.remove('hidden');$('#jobSuccess').classList.add('hidden');$('#jobModal').classList.add('show')}
function bindDynamic(){$$('.hire-provider').forEach(b=>b.onclick=()=>openHire(b.dataset.id));$$('.view-provider').forEach(b=>b.onclick=()=>{renderProfile(b.dataset.id);switchView('profile')});$$('.save-provider').forEach(b=>b.onclick=()=>{b.textContent='♥';toast('Saved to your people')});$$('.quickcat').forEach(b=>b.onclick=()=>{switchView('people');$('#peopleSearch').value=b.dataset.cat;renderPeople()});$$('.apply-job').forEach(b=>b.onclick=()=>{toast('Application sent — demo');b.textContent='Applied';b.disabled=true});$$('.view-job').forEach(b=>b.onclick=()=>toast('Job details opened — demo'));const e=$('#emptyPost');if(e)e.onclick=openJob}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));$$('[data-close]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.close).classList.remove('show')));$$('.modal-wrap').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('show')}));
$('#heroSearchBtn').onclick=()=>{switchView('people');$('#peopleSearch').value=$('#heroSearch').value;renderPeople()};$('#heroSearch').addEventListener('keydown',e=>{if(e.key==='Enter')$('#heroSearchBtn').click()});$$('[data-search]').forEach(b=>b.onclick=()=>{$('#heroSearch').value=b.dataset.search;$('#heroSearchBtn').click()});['peopleSearch','availabilityFilter','distanceFilter','verifyFilter'].forEach(id=>$('#'+id)?.addEventListener(id==='peopleSearch'?'input':'change',renderPeople));
$('#postJobTop').onclick=openJob;$('#postJobSide').onclick=openJob;$('#trustBtn').onclick=()=>$('#trustModal').classList.add('show');$('#sendHire').onclick=()=>{if(!$('#hireTask').value.trim()){toast('Add a short job description first');return}$('#hireFormWrap').classList.add('hidden');$('#hireSuccess').classList.remove('hidden');$('#hireSuccessText').textContent=`${selectedProvider.name} has received your request. In the live product you would now see acceptance, travel, arrival, start and completion status.`};
$('#publishJob').onclick=()=>{const title=$('#jobTitle').value.trim(),desc=$('#jobDesc').value.trim(),budget=$('#jobBudget').value.trim();if(!title||!desc){toast('Add a title and description first');return}jobs.unshift({id:Date.now(),title,category:'New job',distance:'Near you',when:'As soon as possible',budget:budget||'Open to offers',desc});$('#jobFormWrap').classList.add('hidden');$('#jobSuccess').classList.remove('hidden');renderJobs()};$('#viewPostedJob').onclick=()=>{$('#jobModal').classList.remove('show');switchView('jobs')};
$('#availabilityToggle').classList.toggle('on',workerAvailable);$('#availabilityToggle').onclick=()=>{workerAvailable=!workerAvailable;localStorage.setItem('taskwell-available',workerAvailable?'1':'0');$('#availabilityToggle').classList.toggle('on',workerAvailable);toast(workerAvailable?'You are now Available Now':'Available Now turned off')};
$('#sendChat').onclick=()=>{const v=$('#chatInput').value.trim();if(!v)return;const d=document.createElement('div');d.className='bubble me';d.textContent=v;$('.chat-body').appendChild(d);$('#chatInput').value='';$('.chat-body').scrollTop=$('.chat-body').scrollHeight};$('#chatInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#sendChat').click()});$('#profileBack').onclick=()=>switchView('people');$('#notifyBtn').onclick=()=>toast('3 new job and availability notifications');$('#profileBtn').onclick=()=>{switchView('work');toast('Showing your worker dashboard')};
renderHome();renderPeople();renderJobs();